rpc:
  enable: true
  port: 8080
  path: /rpc
  tls:
    enable: false
    cert_file: null
    ket_file: null
log_level: debug
interval: 15
out_put_path: /Users/chigusa
live_rooms: ["https://live.bilibili.com/146910"]