rpc:
  enable: true
  port: :8080
  path: /rpc
  tls:
    enable: false
    cert_file: null
    ket_file: null
log_level: info
interval: 15
out_put_path: ./
live_rooms: ["https://live.bilibili.com/161"]